force-app/main/default/objects/Ado_o__c/Ado_o__c.object-meta.xml
<CustomObject>
    <label>Adoção</label>
    <nameField>
        <displayFormat>ADO-{0000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoção</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ado_o__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Adoção</relationshipLabel>
    <relationshipName>Ado_o</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ado_o__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <label>Pet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pet__c.Ado_o__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Adoção</relationshipLabel>
    <relationshipName>Ado_o</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Historico_de_vacina_o__c/Historico_de_vacina_o__c.object-meta.xml
<CustomObject>
    <label>Historico de vacinação</label>
    <nameField>
        <displayFormat>VAC-{0000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historico de vacinação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_de_vacina_o__c/fields/Local__c.field-meta.xml
<CustomField>
    <fullName>Local__c</fullName>
    <label>Local</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_de_vacina_o__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Historico de vacinação</relationshipLabel>
    <relationshipName>Historico_de_vacina_o</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Ado_o__c.field-meta.xml
<CustomField>
    <fullName>Ado_o__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adoção</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Data_da_ltima_vacina_o__c.field-meta.xml
<CustomField>
    <fullName>Data_da_ltima_vacina_o__c</fullName>
    <label>Data da última vacinação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Especie__c.field-meta.xml
<CustomField>
    <fullName>Especie__c</fullName>
    <label>Especie</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cachorro</fullName>
            </value>
            <value>
                <fullName>Gato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Ra_a__c.field-meta.xml
<CustomField>
    <fullName>Ra_a__c</fullName>
    <label>Raça</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Especie__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vira-lata</fullName>
            </value>
            <value>
                <fullName>Poodle</fullName>
            </value>
            <value>
                <fullName>Siamês</fullName>
            </value>
            <value>
                <fullName>Persa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LembreteVacinacaoTest.cls
@isTest
private class LembreteVacinacaoTest {
    public static String CRON_EXP = '0 0 0 * * ?';
    
    @isTest
    static void testScheduledLembrete() {
   
        List<pet__c> pets = new List<pet__c>();      
        
        for (Integer i=0; i<5; i++) {
            pet__c pet = new pet__c(                
               Name = 'Pet ' + i,        
               especie__c = 'Cachorro',  
               Ra_a__c = 'Vira-lata', 
               Data_da_ltima_vacina_o__c = Date.today().addYears(-3)     
            );
            pets.add(pet);
        }
        insert pets;
        
        Map<Id, pet__c> petMap = new Map<Id, pet__c>(pets);
        List<Id> petIds = new List<Id>(petMap.keySet());
        
        Test.startTest();
        String jobId = System.schedule('Scheduled', CRON_EXP, new LembreteVacinacao());
        
        List<Task> lt = [SELECT Id  FROM Task  WHERE WhatId IN :petIds];       
        System.assertEquals(0, lt.size(), 'Tasks exist');

        Test.stopTest();
    
        lt = [SELECT Id FROM Task  WHERE WhatId IN :petIds];
        System.assertEquals(petIds.size(), lt.size(),'Tasks not created');
        
        pets[0].Data_da_ltima_vacina_o__c = Date.today().addYears(-2);
        update pets;               
    }
    @isTest
    static void testUltimaVacinacao() {
        pet__c pet = new pet__c(                
            Name = 'Pet teste',               
            especie__c = 'Cachorro', 
            Ra_a__c = 'Vira-lata', 
            Data_da_ltima_vacina_o__c = Date.today().addYears(-3)     
        );
        insert pet;  
        
        historico_de_vacina_o__c hvac = new historico_de_vacina_o__c(                
            local__c = 'casa do animal',
            pet__c = pet.Id,                       
            data__c = Date.today()         
        );
        insert hvac;
        
       Contact cont = new Contact( 
            LastName = 'teste',
            Birthdate = Date.today().addYears(-18)          
        );
        insert cont; 
        
        ado_o__c ado = new ado_o__c(                           
            pet__c = pet.Id,    
            Contato__c = cont.Id,
            Status__c = 'Reprovada',
            data__c = Date.today()         
        );
        insert ado;                   
    }    
}